### PR TITLE
New debug overlay with template

### PR DESCRIPTION
**Pull request by anderbubble**
A new debug overlay template serves as an example of how to access all template variables which can also be rendered against any node to display all template variable values.

Signed-off-by: Jonathon Anderson <janderson@ciq.co>

### CODE REVIEW

**Comment by anderbubble** [comment]
I'm marking this as a draft for now because I'd like to add additional documentation in the template; but I wanted to get it in front of @mslacken and @griznog for comment.

**Comment by griznog** [comment]
This is way better than my local attempt which just covers the 5 or so things I care about Right Now (tm). Is it worth setting a long (very long) term goal to have this auto-generated from the data structures/YAML schema as potentially part of automated testing?

**Comment by anderbubble** [comment]
I think I would only want to do it if we could auto-generate the template at build-time. If the template auto-generated at run-time it would negate its usefulness as documentation for how to access the template variables.

**Comment by griznog** [comment]
It's definitely a build-time thing. 

I'm now wondering how hard it'd be to have this file produce something that can be `source`'d in BASH. I'm doing that now with a pitiful subset of values.

**Comment by griznog** [comment]
Also is there any reason this couldn't just live in the `wwinit` overlay? It'd be handy if it was just always there for casual troubleshooting on running nodes without taking an extra step to build an overlay or reboot.

**Comment by anderbubble** [comment]
You don't have to build it or reboot; just `wwctl overlay show --render`. I suppose it could live in wwinit; but that wasn't necessary for my purposes.

**Comment by griznog** [comment]
I include `nodes.conf` on all my nodes, then have downstream local tools that use it for managing/configuring the node and services. Also my runtime overlays get pulled and updated on the live nodes so I can update configs without rebooting. Ultimately having `nodes.conf` and having it update when I pull new overlay versions solves this problem with a large hammer, but because I am still struggling to wrap my head around using `yq` to pull values from YAML into BASH, it's on my to-do list to produce a BASH friendly view of all node settings. 

As I'm thinking this through and typing, I'm now wondering if what I really want is an API call to return the current node config from `warewulfd` rather than sending around all these different overlay files.

**Pull request merged**
