### PR TITLE
Update 10-persistent-net.link.ww

### PR DESCRIPTION
**Pull request by brianphan**
## Description of the Pull Request (PR):

Update Warewulf template to generate a file per network device.

## This fixes or addresses the following GitHub issues:

 - Fixes #

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/main/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/hpcng/warewulf/tree/main/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [main](https://github.com/hpcng/warewulf/tree/main/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by brianphan** [comment]
In my testing, I used the following node configuration: 
```
[root@hpc-lab-control0 ~]# wwctl node list -A
  NODE              FIELD                      PROFILE  VALUE                                                  
  hpc-lab-compute0  Id                         --       hpc-lab-compute0                                       
  hpc-lab-compute0  Comment                    default  This profile is automatically included for each node   
  hpc-lab-compute0  ClusterName                --       --                                                     
  hpc-lab-compute0  ContainerName              --       rocky-8                                                
  hpc-lab-compute0  Ipxe                       --       (default)                                              
  hpc-lab-compute0  RuntimeOverlay             --       (generic)                                              
  hpc-lab-compute0  SystemOverlay              --       (wwinit)                                               
  hpc-lab-compute0  Root                       --       (initramfs)                                            
  hpc-lab-compute0  Discoverable               --       false                                                  
  hpc-lab-compute0  Init                       --       (/sbin/init)                                           
  hpc-lab-compute0  AssetKey                   --       --                                                     
  hpc-lab-compute0  Kernel.Override            --       --                                                     
  hpc-lab-compute0  Kernel.Args                --       (quiet crashkernel=no vga=791 net.naming-scheme=v238)  
  hpc-lab-compute0  Ipmi.Ipaddr                --       --                                                     
  hpc-lab-compute0  Ipmi.Netmask               --       --                                                     
  hpc-lab-compute0  Ipmi.Port                  --       --                                                     
  hpc-lab-compute0  Ipmi.Gateway               --       --                                                     
  hpc-lab-compute0  Ipmi.UserName              --       --                                                     
  hpc-lab-compute0  Ipmi.Password              --       --                                                     
  hpc-lab-compute0  Ipmi.Interface             --       --                                                     
  hpc-lab-compute0  Ipmi.EscapeChar            --       --                                                     
  hpc-lab-compute0  Ipmi.Write                 --       --                                                     
  hpc-lab-compute0  Ipmi.Tags[]                                                                                
  hpc-lab-compute0  Profiles                   --       default                                                
  hpc-lab-compute0  PrimaryNetDev              --       enp8s0                                                 
  hpc-lab-compute0  NetDevs[default].Type      --       (ethernet)                                             
  hpc-lab-compute0  NetDevs[default].OnBoot    --       true                                                   
  hpc-lab-compute0  NetDevs[default].Device    --       ens7                                                   
  hpc-lab-compute0  NetDevs[default].Hwaddr    --       5a:00:04:af:48:74                                      
  hpc-lab-compute0  NetDevs[default].Ipaddr    --       10.0.0.20                                              
  hpc-lab-compute0  NetDevs[default].Ipaddr6   --       --                                                     
  hpc-lab-compute0  NetDevs[default].IpCIDR    --       --                                                     
  hpc-lab-compute0  NetDevs[default].Prefix    --       --                                                     
  hpc-lab-compute0  NetDevs[default].Netmask   --       255.255.252.0                                          
  hpc-lab-compute0  NetDevs[default].Gateway   --       --                                                     
  hpc-lab-compute0  NetDevs[default].MTU       --       --                                                     
  hpc-lab-compute0  NetDevs[default].Primary   --       --                                                     
  hpc-lab-compute0  NetDevs[default].Tags[]                                                                    
  hpc-lab-compute0  NetDevs[external].Type     --       (ethernet)                                             
  hpc-lab-compute0  NetDevs[external].OnBoot   --       true                                                   
  hpc-lab-compute0  NetDevs[external].Device   --       ens3                                                   
  hpc-lab-compute0  NetDevs[external].Hwaddr   --       56:00:04:af:48:74                                      
  hpc-lab-compute0  NetDevs[external].Ipaddr   --       45.77.191.215                                          
  hpc-lab-compute0  NetDevs[external].Ipaddr6  --       --                                                     
  hpc-lab-compute0  NetDevs[external].IpCIDR   --       --                                                     
  hpc-lab-compute0  NetDevs[external].Prefix   --       --                                                     
  hpc-lab-compute0  NetDevs[external].Netmask  --       255.255.254.0                                          
  hpc-lab-compute0  NetDevs[external].Gateway  --       45.77.190.1                                            
  hpc-lab-compute0  NetDevs[external].MTU      --       --                                                     
  hpc-lab-compute0  NetDevs[external].Primary  --       --                                                     
  hpc-lab-compute0  NetDevs[external].Tags[]                                                                   
  hpc-lab-compute0  Tags[]                                                                                     
  hpc-lab-compute0  Disks[]                                                                                    
  hpc-lab-compute0  FileSystems[]  
```
After building the overlays and deploying to the compute node, it generated a file for each interface: 
```
[root@hpc-lab-compute0 network]# pwd 
/etc/systemd/network
[root@hpc-lab-compute0 network]# ls -l 
total 8
-rw-r--r-- 1 root warewulf 246 Dec 14 00:30 10-persistent-net.link-default
-rw-r--r-- 1 root warewulf  55 Dec 14 00:30 10-persistent-net.link-external
```
The content of each file:
```
[root@hpc-lab-compute0 network]# cat 10-persistent-net.link-default 
# This file is autogenerated by warewulf
# Host:   hpc-lab-control0
# Time:   12-14-2023 00:30:47 UTC
# Source: /var/lib/warewulf/overlays/wwinit/etc/systemd/network/10-persistent-net.link.ww
[Match]
MACAddress=5a:00:04:af:48:74
[Link]
Name=ens7
[root@hpc-lab-compute0 network]# cat 10-persistent-net.link-external 
[Match]
MACAddress=56:00:04:af:48:74
[Link]
Name=ens3
```

**Comment by anderbubble** [comment]
@brianphan can you confirm: I think the files need to end with `.link`. Maybe it should be `10-persistent-net-default.link` and `10-persistent-net-external.link`?

Also, can you update CHANGELOG for this?

**Comment by anderbubble** [comment]
@brianphan I rebased and added a few commits.

In testing, I discovered that `eth0` was being set as the default interface for any that didn't have a name set. This seemed incorrect, so I removed `eth0` from the default definition of a network interface.

I also adjusted the template to not use the Warewulf interface name as a default value for the network device name. The interface name is not used as the device name elsewhere in the network configuration templates, so it shouldn't be used here.

@mslacken I'm going to approve this; but I'll wait until tomorrow to merge, in case you have a concern about the change to `defaults.conf`.

**Review by anderbubble — APPROVED** [review]

**Review by mslacken — APPROVED** [review]
Is much more consistent so.

**Pull request merged**
