### PR TITLE
Backwards compatibility fix for network config

### PR DESCRIPTION
**Pull request by gmkurtzer**
This allows backwards compatibility for node configurations that do not specify the network's device name (previously was the netdev member ID).

### CODE REVIEW

**Comment by mslacken** [comment]
This patch still won't help if the node configuration is like:
```
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
    network devices:
      eth0:
        default: false
        hwaddr: ""
        ipaddr: ""
        ipcidr: ""
        prefix: ""
        netmask: 255.255.255.0
        gateway: 192.168.100.1
nodes:
  compute01:
    container name: leap-15
    kernel version: leap15-3-x86
    profiles:
    - default
    network devices:
      eth0:
        default: true
        hwaddr: 52:54:00:87:12:60
        ipaddr: 192.168.100.11
        ipcidr: ""
        prefix: ""
        netmask: ""
```
which worked before are now broken. It seems that now the name needs to be `default` in order to become the default interface,

**Comment by gmkurtzer** [comment]
Hrmm, what isn't working? Using your configuration file I'm getting this:

```
$ sudo ./wwctl node list -a
################################################################################
NODE                 FIELD              PROFILE      VALUE
compute01            Id                 --           compute01
compute01            Comment            default      This profile is automatically included for each node
compute01            Cluster            --           --
compute01            Profiles           --           default
compute01            Discoverable       --           false
compute01            Container          --           leap-15
compute01            Kernel             --           leap15-3-x86
compute01            KernelArgs         --           (quiet crashkernel=no vga=791 rootfstype=rootfs)
compute01            RuntimeOverlay     --           (default)
compute01            SystemOverlay      --           (default)
compute01            Ipxe               --           (default)
compute01            Init               --           (/sbin/init)
compute01            Root               --           (initramfs)
compute01            IpmiIpaddr         --           --
compute01            IpmiNetmask        --           --
compute01            IpmiPort           --           --
compute01            IpmiGateway        --           --
compute01            IpmiUserName       --           --
compute01            IpmiInterface      --           --
compute01            eth0:DEVICE        --           eth0
compute01            eth0:HWADDR        --           52:54:00:87:12:60
compute01            eth0:IPADDR        --           192.168.100.11
compute01            eth0:NETMASK       default      255.255.255.0
compute01            eth0:GATEWAY       default      192.168.100.1
compute01            eth0:TYPE          --           --
compute01            eth0:ONBOOT        --           false
```

This looks right to me,.. hrmm, is it the template that isn't working now?

**Comment by gmkurtzer** [comment]
In reviewing, yes, it must be the template changes. There are several options I think to make the templates smarter, but I'm not sure how much depth you want to go into that.

Thoughts?

**Comment by mslacken** [comment]
Its the templates, I have updated the changelog #239

**Pull request merged**
