### PR TITLE
KERNEL VERSION column is too short

### LINKED ISSUE #690: KERNEL VERSION column is too short
### Version of Warewulf

What version of Warewulf are you using? Run

```
$ wwctl version
wwctl version:	 4.4.0-1.git_81c3192
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.4.0-1.git_81c3192"
```

### Expected behavior

The KERNEL VERSION column in `wwctl container list` should be wide enough to fit a typical EL kernel version. The easiest thing might be to move the column to the end.

### Actual behavior

```
CONTAINER NAME   NODES  KERNEL VERSION   CREATION TIME        MODIFICATION TIME    SIZE
rocky-8          0      4.18.0-372.13.1.el8_6.x86_64 17 Jan 23 23:48 MST  31 Dec 69 17:00 MST  1.0 GiB
```

### What OS/distro are you running

```sh
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### How did you install Warewulf

mockbuild rpm

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

display the output inside an invisible table so that the content in each cell is displayed in a suitable format. 

### This fixes or addresses the following GitHub issues:

 - Fixes #690 

#### Before submitting a PR, make sure you have done the following:

- Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/development/contributing/contributing.html)
- Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/development/CHANGELOG.md) if necessary
- Updated [userdocs](https://github.com/hpcng/warewulf/tree/development/userdocs) if necessary
- Based this PR against the appropriate branch (typically [development](https://github.com/hpcng/warewulf/tree/development/userdocs))
- Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/development/CONTRIBUTORS.md

### Test

before:
```
CONTAINER NAME   NODES  KERNEL VERSION   CREATION TIME        MODIFICATION TIME    SIZE
rocky-8          0      4.18.0-372.13.1.el8_6.x86_64 17 Jan 23 23:48 MST  31 Dec 69 17:00 MST  1.0 GiB
```

after:
```
[vagrant@localhost warewulf]$ sudo wwctl container list
  CONTAINER NAME  NODES  KERNEL VERSION                CREATION TIME        MODIFICATION TIME    SIZE     
  rocky-8         0      4.18.0-425.10.1.el8_7.x86_64  15 Mar 23 08:06 UTC  15 Mar 23 08:07 UTC  2.5 GiB  
```

### CODE REVIEW

**Comment by mslacken** [comment]
Can you please also check `wwctl node/profile list` if its possible to apply the tablewriter functionality there?

**Comment by JasonYangShadow** [comment]
> Can you please also check `wwctl node/profile list` if its possible to apply the tablewriter functionality there?

Okay, thanks! I'll take a look at the `profile/list` function as well.

**Comment by JasonYangShadow** [comment]
```
[vagrant@localhost warewulf]$ sudo wwctl profile list -a
  PROFILE  FIELD            PROFILE  VALUE     
  default  Id               --       default   
  default  comment          --       hello     
  default  cluster          --       --        
  default  container        --       --        
  default  ipxe             --       --        
  default  runtime          --       --        
  default  wwinit           --       --        
  default  root             --       --        
  default  discoverable     --       --        
  default  init             --       --        
  default  asset            --       --        
  default  kerneloverride   --       --        
  default  kernelargs       --       --        
  default  ipmiaddr         --       --        
  default  ipminetmask      --       --        
  default  ipmiport         --       --        
  default  ipmigateway      --       --        
  default  ipmiuser         --       --        
  default  ipmipass         --       --        
  default  ipmiinterface    --       --        
  default  ipmiwrite        --       --        
  default  profile          --       --        
  default  primarynet       --       --        
  default  default:type     --       Ethernet  
  default  default:onboot   --       --        
  default  default:netdev   --       --        
  default  default:hwaddr   --       --        
  default  default:ipaddr   --       --        
  default  default:ipaddr6  --       --        
  default  default:netmask  --       --        
  default  default:gateway  --       --        
  default  default:mtu      --       9000      
[vagrant@localhost warewulf]$ sudo wwctl profile list
  PROFILE NAME  COMMENT/DESCRIPTION  
  default       hello   
```

**Comment by JasonYangShadow** [comment]
@mslacken please help review this PR when you have time. thanks!

**Comment by mslacken** [comment]
I have pushed a test for `wwctl node list`, so it would be nice if you can add a bit more test coverage.
@anderbubble I am fine to merge this, bit then we should open an issue that we need more test coverage here.
For `cotnainer list` more sophisticated tests are needed as here temporary files are needed.

**Comment by JasonYangShadow** [comment]
> I have pushed a test for `wwctl node list`, so it would be nice if you can add a bit more test coverage. @anderbubble I am fine to merge this, bit then we should open an issue that we need more test coverage here. For `cotnainer list` more sophisticated tests are needed as here temporary files are needed.

@mslacken thanks for the test case! Sorry for not adding required test cases, I will add more.

**Comment by mslacken** [comment]
@JasonYangShadow we just started to use testing on a broader base, so no need to feel sorry. Also testing cobra applications is tricky.

**Comment by JasonYangShadow** [comment]
@mslacken I have added two test cases for `profile list` and `container list`.

**Review by mslacken — APPROVED** [review]
Great work, thanks

**Pull request merged**
