### PR TITLE
don't panic on malformed passwd

### LINKED ISSUE #527: panic during syncusers
Encountered this panic:

```
# wwctl container syncuser rocky-8-split
panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
github.com/hpcng/warewulf/internal/pkg/container.createPasswdMap({0xd48675, 0xb})
	/builddir/build/BUILD/warewulf-4.3.0/internal/pkg/container/syncuids.go:225 +0x632
github.com/hpcng/warewulf/internal/pkg/container.SyncUids({0x7ffff05f8183, 0xd}, 0x1)
	/builddir/build/BUILD/warewulf-4.3.0/internal/pkg/container/syncuids.go:43 +0x7b
github.com/hpcng/warewulf/internal/app/wwctl/container/syncuser.CobraRunE(0x15e64e0, {0xc00006e520, 0x1, 0x1})
	/builddir/build/BUILD/warewulf-4.3.0/internal/app/wwctl/container/syncuser/main.go:17 +0x6e
github.com/spf13/cobra.(*Command).execute(0x15e64e0, {0xc00006e4f0, 0x1, 0x1})
	/builddir/build/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x15e3d80)
	/builddir/build/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/warewulf-4.3.0/vendor/github.com/spf13/cobra/command.go:895
main.main()
	/builddir/build/BUILD/warewulf-4.3.0/cmd/wwctl/main.go:13 +0x25
```

Using the RPM from GitHub.

```
# wwctl version
4.3.0-1.git_235c23c
```

I'm still investigating the circumstances.

### PR DESCRIPTION
**Pull request by mslacken**
added a test for malformed passwd and fixed the panic

close #527

Signed-off-by: Christian Goll <cgoll@suse.com>

### CODE REVIEW

**Comment by mslacken** [comment]
The changes look big, but were caused by the auto formating of the editor.

**Comment by mslacken** [comment]
@anderbubble  I had to use this patch in order to get an actual `rocky9.2` container imported, so it should go into 4.5.x

**Comment by anderbubble** [comment]
That's odd. I have definitely imported Rocky 9.2 images in the past.

I'll check it out.

**Review by anderbubble — APPROVED** [review]
Rebased and updated change log. Looks good to me.

**Pull request merged**
