### PR TITLE
Fix empty kernel modules and drivers

### LINKED ISSUE #836: kmod don't include anything
### Version of Warewulf

development branch

### Expected behavior

If a kernel is imported `kmod.img`  should include all the modules and firmare

### Actual behavior

`kmod.img` is empty

### Reason

The `filepath.Match ` in https://github.com/hpcng/warewulf/blob/866348bc932d9c4193d83e6f67b9b9a06bd868a8/internal/pkg/util/util.go#L339 does match the exact pattern, so 
`/lib/firmware/foo` would not be matched by `/lib/firmware`.

### PR DESCRIPTION
**Pull request by mslacken**
- added test and refactored kernel.Build
- fixed kmod creation

close #836

### CODE REVIEW

**Review by anderbubble — COMMENTED** [review]
I admit, I'm a bit outside of my experience here. The code looks reasonable enough; but when I imported a kernel from a container and tried to list `kmods.img`, it appears empty to me.

```
$ sudo wwctl kernel import --container rocky-8 --detect
Found kernel at: /var/lib/warewulf/chroots/rocky-8/rootfs/boot/vmlinuz-4.18.0-372.13.1.el8_6.x86_64
Created image for rocky-8 drivers: /var/lib/warewulf/kernel/rocky-8/kmods.img
Compressed image for rocky-8 drivers: /var/lib/warewulf/kernel/rocky-8/kmods.img.gz
rocky-8: Finished kernel build

$ sudo file /var/lib/warewulf/kernel/rocky-8/kmods.img
/var/lib/warewulf/kernel/rocky-8/kmods.img: ASCII cpio archive (SVR4 with no CRC)

$ sudo cpio -civt </var/lib/warewulf/kernel/rocky-8/kmods.img
1 block
$ sudo cpio -ivt </var/lib/warewulf/kernel/rocky-8/kmods.img
1 block
```

Am I just looking at it incorrectly? Or is `kmods.img` still incorrectly empty? (Or _should_ it be empty here?)

**Comment by griznog** [comment]
Any chance this could include a way to just disable `kmods.img` for a given container? If we have to have it it'd be nice if there was at least a way to opt-out of it. Since it's use case (running non-distro kernels) is really a corner case relative to a typical cluster setup, requiring opting-in instead of allowing opting-out might be even better.

**Comment by mslacken** [comment]
Kmods is disabled per default and only used if kernel.override is set.

**Comment by griznog** [comment]
> Kmods is disabled per default and only used if kernel.override is set.

Sorry for the noise, I managed to completely miss the changes for that and I've been filtering out the kmod errors I used to get. :blush:

**Comment by anderbubble** [comment]
@mslacken could you rebase this on current main?

**Comment by anderbubble** [comment]
I tested this again, and it appears to work.

```
[janderson@rocky FixKmod]$ sudo wwctl kernel import --container rocky-9.3 --detect
Found kernel at: /var/lib/warewulf/chroots/rocky-9.3/rootfs/lib/modules/5.14.0-362.13.1.el9_3.aarch64/vmlinuz
Created image for rocky-9.3 drivers: /var/lib/warewulf/provision/kernel/rocky-9.3/kmods.img
Compressed image for rocky-9.3 drivers: /var/lib/warewulf/provision/kernel/rocky-9.3/kmods.img.gz
rocky-9.3: Finished kernel build
[janderson@rocky FixKmod]$ cpio -zvt </var/lib/warewulf/provision/kernel/rocky-9.3/kmods.img.gz
cpio: invalid option -- 'z'
Try 'cpio --help' or 'cpio --usage' for more information.
[janderson@rocky FixKmod]$ cpio -vt </var/lib/warewulf/provision/kernel/rocky-9.3/kmods.img
-rw-r--r--   1 root     root          168 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/.vmlinuz.hmac
-rw-------   1 root     root      5958827 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/System.map
-rw-r--r--   1 root     root       200194 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/config
drwxr-xr-x  11 root     root            0 Jan 16 00:03 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb
drwxr-xr-x   2 root     root            0 Jan 16 00:03 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/amd
-rwxr-xr-x   1 root     root         8097 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/amd/amd-overdrive-rev-b0.dtb
-rwxr-xr-x   1 root     root         8089 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/amd/amd-overdrive-rev-b1.dtb
-rwxr-xr-x   1 root     root         5927 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/amd/amd-overdrive.dtb
-rwxr-xr-x   1 root     root         8109 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/amd/husky.dtb
drwxr-xr-x   2 root     root            0 Jan 16 00:03 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/apm
-rwxr-xr-x   1 root     root        16175 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/apm/apm-merlin.dtb
-rwxr-xr-x   1 root     root        21884 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/apm/apm-mustang.dtb
drwxr-xr-x   2 root     root            0 Jan 16 00:03 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/arm
-rwxr-xr-x   1 root     root         5265 Dec 13 11:19 lib/modules/5.14.0-362.13.1.el9_3.aarch64/dtb/arm/foundation-v8-gicv3-psci.dtb
[...]
827996 blocks
```

**Comment by anderbubble** [comment]
I also checked with my original rocky-8 container, and that imported correctly as well.

**Review by anderbubble — APPROVED** [review]

**Pull request merged**
