### PR TITLE
Typo in setup.rst (then vs. than)

### PR DESCRIPTION
**Pull request by novosirj**
## Description of the Pull Request (PR):

Minor typo correction

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/development/contributing/contributing.html)
- [x] Based this PR against the appropriate branch (typically [development](https://github.com/hpcng/warewulf/tree/development/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/development/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
Thanks for the catch!

**Comment by novosirj** [comment]
All of those "make sure you..." things came up after I submitted the PR, but I figured this is probably simple enough that I didn't need to do it over. I expect I can contribute some more later, though, so I can go through that part later.

**Comment by anderbubble** [comment]
@novosirj you do need to at least sign off the commit. Could you update your commit and re-push?

You can also add your name to CONTRIBUTORS; but if you don't want to for this small change, that should be fine.

```
git commit --amend --signoff
git push --force
```

**Comment by novosirj** [comment]
I cheated and did it via the web. I'd have to refresh my memory on how to do that stuff with a new repository where I've not interacted before from the command line. I can do that in the near future though.

**Comment by anderbubble** [comment]
Please do, @novosirj. I know it seems pedantic, but we need to make sure we have all contributions signed-off.

If  you can edit the existing commit, all you really need to do is add a line like this to the bottom of your commit message:

```
Signed-off-by: Jonathon Anderson <janderson@ciq.com>
```

Or just confirm here that you agree to the terms in https://github.com/hpcng/warewulf/blob/development/DCO.txt and I'll add sign-off on it myself.

Sorry for the delay: we're still working out best practices here, and I've been traveling.

**Comment by novosirj** [comment]
Oh, not pedantic at all -- we work with computers! 

I'll take care of that straight away.

**Comment by novosirj** [comment]
I appear to have fixed it and refreshed my memory on git somewhat.

FWIW, you cannot edit a commit in the GUI, as far as I can tell from what I've read.

**Comment by anderbubble** [comment]
Thanks!

**Review by anderbubble — COMMENTED** [review]
lgtm

**Pull request merged**
