### PR TITLE
[WIP] Add output [yaml | json | csv | text] for list subcommand

### LINKED ISSUE #447: add `--output [text|csv|json|yaml]` option for `wwctl` commands that produce output.
It'd be nice when writing tools/scripts that use `wwctl` output if there were some script-friendly formats available that don't require pulling apart the human readable default output. I'm hoping that at least JSON will be trivial to implement once things move to the API model, which will need to pass things around as JSON (or YAML?) by design.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

adding multiple output format support

this PR will add multiple output format support for wwctl list sub-commands.

example:

`container list`
```
root@ubuntu:/home/vagrant/warewulf# wwctl container list
  CONTAINER NAME  NODES  KERNEL VERSION                CREATION TIME        MODIFICATION TIME    SIZE     
  rocky8          0      4.18.0-513.9.1.el8_9.aarch64  02 Jan 24 07:23 UTC  01 Jan 70 00:00 UTC  1.2 GiB  
root@ubuntu:/home/vagrant/warewulf# wwctl container list -o yaml
containers:
    - createDate: "1704180191"
      kernelVersion: 4.18.0-513.9.1.el8_9.aarch64
      name: rocky8
      size: "1266908641"
root@ubuntu:/home/vagrant/warewulf# wwctl container list -o json
{"containers":[{"name":"rocky8","kernelVersion":"4.18.0-513.9.1.el8_9.aarch64","createDate":1704180191,"size":1266908641}]}
root@ubuntu:/home/vagrant/warewulf# wwctl container list -o csv
CONTAINER NAME,NODES,KERNEL VERSION,CREATION TIME,MODIFICATION TIME,SIZE
rocky8,0,4.18.0-513.9.1.el8_9.aarch64,02 Jan 24 07:23 UTC,01 Jan 70 00:00 UTC,1.2 GiB
root@ubuntu:/home/vagrant/warewulf# wwctl container list -o text
  CONTAINER NAME  NODES  KERNEL VERSION                CREATION TIME        MODIFICATION TIME    SIZE     
  rocky8          0      4.18.0-513.9.1.el8_9.aarch64  02 Jan 24 07:23 UTC  01 Jan 70 00:00 UTC  1.2 GiB  
```

`profile list`
```
root@ubuntu:/home/vagrant/warewulf# wwctl profile list
  PROFILE NAME  COMMENT/DESCRIPTION                                   
  default       This profile is automatically included for each node  
root@ubuntu:/home/vagrant/warewulf# wwctl profile list -o yaml
profiles:
    - profileSimple:
        comment: This profile is automatically included for each node
        profileName: default
root@ubuntu:/home/vagrant/warewulf# wwctl profile list -o json
{"profiles":[{"ProfileEntry":{"ProfileSimple":{"profile_name":"default","comment":"This profile is automatically included for each node"}}}]}
root@ubuntu:/home/vagrant/warewulf# wwctl profile list -o csv
PROFILE NAME,COMMENT/DESCRIPTION
default,This profile is automatically included for each node
root@ubuntu:/home/vagrant/warewulf# wwctl profile list -a -o csv
PROFILE,FIELD,PROFILE,VALUE
default,Id,--,default
default,Comment,--,This profile is automatically included for each node
root@ubuntu:/home/vagrant/warewulf# wwctl profile list -a -o yaml
profiles:
    - profileFull:
        field: Id
        profileName: default
        source: --
        value: default
    - profileFull:
        field: Comment
        profileName: default
        source: --
        value: This profile is automatically included for each node
root@ubuntu:/home/vagrant/warewulf# wwctl profile list -a -o text
  PROFILE  FIELD    PROFILE  VALUE                                                 
  default  Id       --       default                                               
  default  Comment  --       This profile is automatically included for each node  
```

current impacted list sub-commands are:
1. `container list`
2. `kernel list`
3. `node list`
4. `profile list`
5. `overlay list`

Besides, this PR also refactors current list related sub-commands, using protobuf message as the standard input and output, which can be used for all supported formats. 

**one issue**:
This PR introduces one package, https://github.com/bufbuild/protoyaml-go, which will require minimal go version of 1.19. This will break current CI/CD 1.18 related builds. I've made changes in the Github action file, please be advised. 

## This fixes or addresses the following GitHub issues:

 - Fixes #447 

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/hpcng/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/hpcng/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
@JasonYangShadow thanks for calling out that this would increase the minimum golang version. I'll mark it for discussion and raise the question in Slack.

**Review by anderbubble — CHANGES_REQUESTED** [review]
I noticed that container yaml output has unnecessary indentation. Do you know why? (Not a big deal; just curious why it appears to be inconsistent.)

```
$ sudo wwctl container list --output=yaml
containers:
    - createDate: "1686016960"
      name: alpine
      size: "7726031"
    - createDate: "1674024538"
      kernelVersion: 4.18.0-372.13.1.el8_6.x86_64
      modDate: "1700982998"
      name: rocky-8
      size: "2578381730"
    - createDate: "1685380050"
      kernelVersion: 4.18.0-425.19.2.el8_7.aarch64
      modDate: "1700983011"
      name: rockylinux-8.7
      size: "2720218070"
```

The node list should be formatted by node; not wrapped with nodeentry and nodesimple.

So in stead of this

```
$ sudo wwctl node list --output=yaml
nodes:
- nodeentry:
    nodesimple:
      nodename: n1
      profiles: default
      network: eth0, eth0.123
- nodeentry:
    nodesimple:
      nodename: node1
      profiles: testdefault
      network: predictable_name, vlan
```

It should look like this:

```
$ sudo wwctl node list --output=yaml
nodes:
- nodename: n1
  profiles: default
  network: eth0, eth0.123
- nodename: node1
  profiles: testdefault
  network: predictable_name, vlan
```

And then if you add `--all` all those fields should be collapsed as a single object; not returned as distinct objects.

```
$ sudo wwctl node list --output=yaml --all n1
nodes:
- nodeentry:
    nodefull:
      nodename: n1
      field: Id
      profile: --
      value: n1
- nodeentry:
    nodefull:
      nodename: n1
      field: Comment
      profile: default
      value: This profile is automatically included for each node
[...]
```

Should be

```
$ sudo wwctl node list --output=yaml --all n1
nodes:
- nodename: n1
  Id: n1
  Comment: This profile is automatically included for each node
[...]
```

Same for profile. And overlays.

And when overlays is listed with contents shown, the contents should be collated as a single list within the overlay.

**Comment by anderbubble** [comment]
Meanwhile: the TSC is supportive of increasing the minimum golang version. I'll want to make sure it still builds on Rocky 8, but I think even if we break EL7 compatibility that's probably fine by now.

**Comment by JasonYangShadow** [comment]
> Meanwhile: the TSC is supportive of increasing the minimum golang version. I'll want to make sure it still builds on Rocky 8, but I think even if we break EL7 compatibility that's probably fine by now.
> 
> [warewulf.slack.com/archives/C066QH3RK39/p1704384348308089](https://warewulf.slack.com/archives/C066QH3RK39/p1704384348308089)
> Screenshot 2024-01-08 at 9 48 12 AM

thanks! this would be great. anyway, let's keep tracking and verifying whether it can be upgraded or not.

**Comment by JasonYangShadow** [comment]
> I noticed that container yaml output has unnecessary indentation. Do you know why? (Not a big deal; just curious why it appears to be inconsistent.)
> 
> ```
> $ sudo wwctl container list --output=yaml
> containers:
>     - createDate: "1686016960"
>       name: alpine
>       size: "7726031"
>     - createDate: "1674024538"
>       kernelVersion: 4.18.0-372.13.1.el8_6.x86_64
>       modDate: "1700982998"
>       name: rocky-8
>       size: "2578381730"
>     - createDate: "1685380050"
>       kernelVersion: 4.18.0-425.19.2.el8_7.aarch64
>       modDate: "1700983011"
>       name: rockylinux-8.7
>       size: "2720218070"
> ```
> 
> The node list should be formatted by node; not wrapped with nodeentry and nodesimple.
> 
> So in stead of this
> 
> ```
> $ sudo wwctl node list --output=yaml
> nodes:
> - nodeentry:
>     nodesimple:
>       nodename: n1
>       profiles: default
>       network: eth0, eth0.123
> - nodeentry:
>     nodesimple:
>       nodename: node1
>       profiles: testdefault
>       network: predictable_name, vlan
> ```
> 
> It should look like this:
> 
> ```
> $ sudo wwctl node list --output=yaml
> nodes:
> - nodename: n1
>   profiles: default
>   network: eth0, eth0.123
> - nodename: node1
>   profiles: testdefault
>   network: predictable_name, vlan
> ```
> 
> And then if you add `--all` all those fields should be collapsed as a single object; not returned as distinct objects.
> 
> ```
> $ sudo wwctl node list --output=yaml --all n1
> nodes:
> - nodeentry:
>     nodefull:
>       nodename: n1
>       field: Id
>       profile: --
>       value: n1
> - nodeentry:
>     nodefull:
>       nodename: n1
>       field: Comment
>       profile: default
>       value: This profile is automatically included for each node
> [...]
> ```
> 
> Should be
> 
> ```
> $ sudo wwctl node list --output=yaml --all n1
> nodes:
> - nodename: n1
>   Id: n1
>   Comment: This profile is automatically included for each node
> [...]
> ```
> 
> Same for profile. And overlays.
> 
> And when overlays is listed with contents shown, the contents should be collated as a single list within the overlay.

it's because csv and text have different output procedures against yaml and json. Yaml and Json outputs are more easier and without manual manipulation. Anyway, I also think that the yaml and json outputs are a bit of messy (too many nested structs), will figure out a way of outputting the results more flatten.

**Comment by anderbubble** [comment]
> will figure out a way of outputting the results more flatten.

btw, I think I understood that you did a lot of work to get this passed through wwapi; be advised that it is our intent, in v4.6.0, to decouple wwapi from wwctl. Both should call into a standard library of internal code, of course; but wwctl shouldn't need to pass through grpc semantics or the functions otherwise in wwctl. So, if that makes it easier, feel free to abandon that coordination for this.

**Comment by JasonYangShadow** [comment]
> > will figure out a way of outputting the results more flatten.
> 
> btw, I think I understood that you did a lot of work to get this passed through wwapi; be advised that it is our intent, in v4.6.0, to decouple wwapi from wwctl. Both should call into a standard library of internal code, of course; but wwctl shouldn't need to pass through grpc semantics or the functions otherwise in wwctl. So, if that makes it easier, feel free to abandon that coordination for this.

thanks! noted.

**Comment by mslacken** [comment]
> > will figure out a way of outputting the results more flatten.
> 
> btw, I think I understood that you did a lot of work to get this passed through wwapi; be advised that it is our intent, in v4.6.0, to decouple wwapi from wwctl. Both should call into a standard library of internal code, of course; but wwctl shouldn't need to pass through grpc semantics or the functions otherwise in wwctl. So, if that makes it easier, feel free to abandon that coordination for this.

1. The API is broken here as it should give for any list call only the complete list of all elements back (as yaml or json) and then client (in this case wwctl) filters the information out, based on what the user has requested.
2. The output of of at least `node/profile list` is formal `yaml` or `json` but it's no structured in a sane and sensible way. Take e.g 
```
Nodes:
- NodeName: n01
  Field: Id
  Profile: --
  Value: n01
- NodeName: n01
  Field: Comment
  Profile: default
  Value: This profile is automatically included for each node
- NodeName: n01
  Field: ContainerName
  Profile: default
  Value: leap15.5
- NodeName: n01
  Field: Ipxe
  Profile: --
  Value: (default)
```
this is just list of every value in of the node, where the Nodename is part of the list. Better would be something like
```
Nodes:
  - NodeName: n01
     Fields:
     - Field: Comment
       Profile: default
       Value: This profile is automatically included for each node
```
or to be even more close  on the yaml we have in the configuration
```
Nodes:
  n01:
   Comment:
      Value: This profile is automatically included for each node
      Profile: This profile is automatically included for each node
```
also having fields like `Field: Kernel.Args` is wrong as `Kernel` is a subset of node.

**Comment by JasonYangShadow** [comment]
> > > will figure out a way of outputting the results more flatten.
> > 
> > 
> > btw, I think I understood that you did a lot of work to get this passed through wwapi; be advised that it is our intent, in v4.6.0, to decouple wwapi from wwctl. Both should call into a standard library of internal code, of course; but wwctl shouldn't need to pass through grpc semantics or the functions otherwise in wwctl. So, if that makes it easier, feel free to abandon that coordination for this.
> 
>     1. The API is broken here as it should give for any list call only the complete list of all elements back (as yaml or json) and then client (in this case wwctl) filters the information out, based on what the user has requested.
> 
>     2. The output of of at least `node/profile list` is formal `yaml` or `json` but it's no structured in a sane and sensible way. Take e.g
> 
> 
> ```
> Nodes:
> - NodeName: n01
>   Field: Id
>   Profile: --
>   Value: n01
> - NodeName: n01
>   Field: Comment
>   Profile: default
>   Value: This profile is automatically included for each node
> - NodeName: n01
>   Field: ContainerName
>   Profile: default
>   Value: leap15.5
> - NodeName: n01
>   Field: Ipxe
>   Profile: --
>   Value: (default)
> ```
> 
> this is just list of every value in of the node, where the Nodename is part of the list. Better would be something like
> 
> ```
> Nodes:
>   - NodeName: n01
>      Fields:
>      - Field: Comment
>        Profile: default
>        Value: This profile is automatically included for each node
> ```
> 
> or to be even more close on the yaml we have in the configuration
> 
> ```
> Nodes:
>   n01:
>    Comment:
>       Value: This profile is automatically included for each node
>       Profile: This profile is automatically included for each node
> ```
> 
> also having fields like `Field: Kernel.Args` is wrong as `Kernel` is a subset of node.

this `Field: Kernel.Args` is generated from 
https://github.com/JasonYangShadow/warewulf/blob/7b1850ff12bb0399f662ff68bbb4b201159a0765/internal/pkg/node/list.go#L74
but I think we can do some optimization for this field name as suggested.

**Comment by JasonYangShadow** [comment]
after refactoring the `node list`
it'll show the output as this
```
root@ubuntu:/home/vagrant/warewulf# wwctl node list -a
  NODE  FIELD           PROFILE  VALUE                                                  
  n1    Id              --       n1                                                     
  n1    Comment         default  This profile is automatically included for each node   
  n1    Ipxe            --       (default)                                              
  n1    RuntimeOverlay  --       (generic)                                              
  n1    SystemOverlay   --       (wwinit)                                               
  n1    Root            --       (initramfs)                                            
  n1    Init            --       (/sbin/init)                                           
  n1    KernelArgs      --       (quiet crashkernel=no vga=791 net.naming-scheme=v238)  
  n1    Profiles        --       default                                                
  n1    Tags[tag]       --       1                                                      
  n1    Tags[xxx]       --       1                                                      
  n1    Tags[email]     --       newval                                                 
  n2    Id              --       n2                                                     
  n2    Comment         default  This profile is automatically included for each node   
  n2    Ipxe            --       (default)                                              
  n2    RuntimeOverlay  --       (generic)                                              
  n2    SystemOverlay   --       (wwinit)                                               
  n2    Root            --       (initramfs)                                            
  n2    Init            --       (/sbin/init)                                           
  n2    KernelArgs      --       (quiet crashkernel=no vga=791 net.naming-scheme=v238)  
  n2    Profiles        --       default                                                
  n2    Tags[email]     default  profile                    
```

```                            
root@ubuntu:/home/vagrant/warewulf# wwctl node list -a -o yaml
Nodes:
  n1:
  - Field: Id
    Profile: --
    Value: n1
  - Field: Comment
    Profile: default
    Value: This profile is automatically included for each node
  - Field: Ipxe
    Profile: --
    Value: (default)
  - Field: RuntimeOverlay
    Profile: --
    Value: (generic)
  - Field: SystemOverlay
    Profile: --
    Value: (wwinit)
  - Field: Root
    Profile: --
    Value: (initramfs)
  - Field: Init
    Profile: --
    Value: (/sbin/init)
  - Field: KernelArgs
    Profile: --
    Value: (quiet crashkernel=no vga=791 net.naming-scheme=v238)
  - Field: Profiles
    Profile: --
    Value: default
  - Field: Tags[xxx]
    Profile: --
    Value: "1"
  - Field: Tags[email]
    Profile: --
    Value: newval
  - Field: Tags[tag]
    Profile: --
    Value: "1"
  n2:
  - Field: Id
    Profile: --
    Value: n2
  - Field: Comment
    Profile: default
    Value: This profile is automatically included for each node
  - Field: Ipxe
    Profile: --
    Value: (default)
  - Field: RuntimeOverlay
    Profile: --
    Value: (generic)
  - Field: SystemOverlay
    Profile: --
    Value: (wwinit)
  - Field: Root
    Profile: --
    Value: (initramfs)
  - Field: Init
    Profile: --
    Value: (/sbin/init)
  - Field: KernelArgs
    Profile: --
    Value: (quiet crashkernel=no vga=791 net.naming-scheme=v238)
  - Field: Profiles
    Profile: --
    Value: default
  - Field: Tags[email]
    Profile: default
    Value: profile
```

**Comment by mslacken** [comment]
You are fixing the problem for `wwtcl node list` on the wrong end. Instead of meddling with every single entry you could simply encode the json or yaml in the `internal/pkg/api/node/list.go` and just send the yml string back. In this file you can simple get the list of nodes, including its entries, see the PR
https://github.com/hpcng/warewulf/pull/1050
where I solved this for yaml. Also if a user requests a yaml, the requester is responsible of what he gets out of the data, so there is no need for extra handling the network and ipmi switches of the list command.

**Comment by JasonYangShadow** [comment]
@anderbubble @griznog 
Regarding this enhancement, should the json/yaml/csv formats stick to original cli output result? (we might need to define new structs to customize outputs to mimic original cli output). This way will give us the exact same output fields as original cli output has. `wwctl list -a` has the same fieds with `wwctl list -a -o yaml` but with different format. 

Or we treat `yaml/csv/json` as separated formats, this means @mslacken (please correct me if I am wrong here) different flags have no affacts for `yaml/csv/json`,  for example `wwctl node list --long/--all/--ipmi...` won't affact `yaml/csv/json` output.

**Comment by griznog** [comment]
@JasonYangShadow sorry I'm getting to this pretty late in the game. I'd go back to what the purpose of getting a node config in yaml/json format is, for which I can only think of two cases:

1. I want the exact node config as it appears in the `nodes.conf` file, before having profiles merged into it to pass this to a tool which will use it to verify or modify that config.
2. I want a complete merged node config with all overlays merged to use to verify that what I think is happening is actually happening and to use with tools that run post-boot on the node and configure something or perhaps generate/manage something to be added to the overlays. 

`wwctl node list` has never been interesting to me as a command, I can easily just read `nodes.conf` and get what I want to the point of it being straightforward to even reproduce the profile merging behavior in a local script. I don't think there needs to be any fancy formatting of any of this. Just what is the node config before/after profile merging in valid yaml/json with or without indentation. If I want indentation, `wwctl node list --json | jq` does a nice job and piping to `yq` does the same for yaml but the primary purpose for this from my view is feeding the result into some local tool or hack. 

With respect to `csv`, I don't see the point in even trying to output `csv`. Even now the structure of a config is too complex to be flattened in a useful way and if/when we finally support truly unstructured configs, with deep nested config data, it'll be even more impossible to flatten into a simple set of rows/columns.

If anything I'd say drop `csv` and add `html` as a format, presenting a nodes config in a nice HTML table. I find it super annoying that there are a lot of online tools that do a pretty good job of blanket converting a YAML file to an HTML table, but none of them open source the tools they use to do it and the available open source tools for it are awful.

**Comment by anderbubble** [comment]
@JasonYangShadow since @griznog was the original author of #447, my inclination is to remove the csv requirement, not add html (@griznog I say open a new issue for a later epic if you want to pursue that) and prefer the "merged" format (as @griznog put it, though I think he meant to refer to profiles rather than overlays) for this PR. This YAML output should be _valid_ for insertion back into `nodes.conf`, should one want to do that. _maybe_ use comments to indicate when a given value is coming from a profile rather than from the node definition itself.

If we want to be able to output what's in nodes.conf without expanding attribute definitions from profiles, I suggest that that also should be a new issue for a later epic. That'll let us keep the scope from growing and let us iterate on the solution.

@griznog what do you think?

**Comment by griznog** [comment]
@anderbubble agree 100%. Most important use case if a dump of merged configs.

**Comment by JasonYangShadow** [comment]
Thanks you all for the comments and suggestion. 
I've created a new PR containing `node | profile list --yaml | --json` here, we are outputting `NodeInfo` struct directly. 
https://github.com/hpcng/warewulf/pull/1053

**Pull request closed without merging**
