### PR TITLE
Update iPXE build script

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

It has recently come to my attention that the builds of iPXE that come with Rocky Linux still have significant bugs that inhibit the use of large images, and omit support for `imgextract` besides.

While I still think deploying Warewulf to use the OS iPXE by default is still the right thing, I wanted to improve the build script so that it's easier to build iPXE locally.

This PR replaces `ipxe-update.sh` with `scripts/build-ipxe.sh`.

* correctly builds for arm64
* supports additional configuration from environment variables
* intended for use on an installed system

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/main/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/hpcng/warewulf/tree/main/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [main](https://github.com/hpcng/warewulf/tree/main/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Review by mslacken — CHANGES_REQUESTED** [review]
The old script had a usage/-h option, the new not. Can you please bring this back?

**Comment by anderbubble** [comment]
@mslacken agreed, and thanks for the prompting.

**Comment by anderbubble** [comment]
@mslacken I added support for a `-h` argument. How about now?

**Review by mslacken — APPROVED** [review]
with help now

**Pull request merged**
