### PR TITLE
wwctl overlay import: transparently create parent directories

### LINKED ISSUE #608: wwctl overlay import: transparently create parent directories
During `wwctl overlay import`, if parent directories do not exist, create them, perhaps with an optional `-p`, `--parents`.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

wwctl overlay import: transparently create parent directories

### This fixes or addresses the following GitHub issues:

 - Fixes #608 

#### Before submitting a PR, make sure you have done the following:

- Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/development/contributing/contributing.html)
- Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/development/CHANGELOG.md) if necessary
- Updated [userdocs](https://github.com/hpcng/warewulf/tree/development/userdocs) if necessary
- Based this PR against the appropriate branch (typically [development](https://github.com/hpcng/warewulf/tree/development/userdocs))
- Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/development/CONTRIBUTORS.md

### CODE REVIEW

**Comment by JasonYangShadow** [comment]
@mslacken it looks like that to write a main_test for this code we need to run it with privilege (sudo make test-it). As it'll create folders inside `/var/local/warewulf/overlays/`

**Comment by mslacken** [comment]
> @mslacken it looks like that to write a main_test for this code we need to run it with privilege (sudo make test-it). As it'll create folders inside `/var/local/warewulf/overlays/`

No, as in the actual development branch all the paths can be configured in `warewulf.conf` you can point the overlay path to a writeable path. Apptainer has some boilerplate code for this tests in [conveyorPacker_yum.go](https://github.com/apptainer/apptainer/blob/main/internal/pkg/build/sources/conveyorPacker_yum.go)[conveyorPacker_yum.go](https://github.com/apptainer/apptainer/blob/main/internal/pkg/build/sources/conveyorPacker_yum.go).
For reading in an arbitrary `warewulf.conf` see https://github.com/hpcng/warewulf/blob/0f2fcb326f56eb2dfd48ded9457eb613783a97e3/internal/app/wwctl/node/add/main_test.go#L244 and following line.

**Comment by JasonYangShadow** [comment]
@mslacken I've added a test case for the changes

**Comment by anderbubble** [comment]
@JasonYangShadow I have since discovered that `wwctl overlay edit` has a `--parents` flag to do a similar thing; it might be worth having this new behavior occur only when `--parents` is specified to `wwctl overlay import`.

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow I have since discovered that `wwctl overlay edit` has a `--parents` flag to do a similar thing; it might be worth having this new behavior occur only when `--parents` is specified to `wwctl overlay import`.

I also added `--parents` option to `import` subcommand, https://github.com/hpcng/warewulf/pull/777/commits/c1df3f7ca20d28977dcc0edef94f0f2ce52ec450

**Comment by anderbubble** [comment]
Looks good to me.

```console

[janderson@rocky warewulf]$ sudo wwctl overlay list debug -l
PERM MODE    UID GID   SYSTEM-OVERLAY     FILE PATH
-rwxr-xr-x     0 977   debug              /warewulf/
-rw-r--r--     0 0     debug              /warewulf/exports.ww
-rw-r--r--     0 977   debug              /warewulf/template-variables.md.ww

[janderson@rocky warewulf]$ sudo wwctl overlay import debug /etc/os-release 
ERROR  : Could not create destination file /var/lib/warewulf/overlays/debug/etc/os-release: open /var/lib/warewulf/overlays/debug/etc/os-release: no such file or directory
ERROR: could not copy file into overlay: open /var/lib/warewulf/overlays/debug/etc/os-release: no such file or directory
[janderson@rocky warewulf]$ sudo wwctl overlay import debug /etc/os-release --parents
[janderson@rocky warewulf]$ sudo wwctl overlay list debug -l
PERM MODE    UID GID   SYSTEM-OVERLAY     FILE PATH
-rw-r--r--     0 0     debug              /etc/
-rw-r--r--     0 0     debug              /etc/os-release
-rwxr-xr-x     0 977   debug              /warewulf/
-rw-r--r--     0 0     debug              /warewulf/exports.ww
-rw-r--r--     0 977   debug              /warewulf/template-variables.md.ww
```

**Pull request merged**
