### PR TITLE
Reorganize, document, and test the node package

### PR DESCRIPTION
**Pull request by anderbubble**
An attempt to reorganize, document, and test the node package.

- [ ] refactors
  - [X] move NoValue to internal/pkg/api/node/methods.go
  - [X] New -> ReadNodeYaml
  - [X] rename NetDevs -> NetDevConf
  - [x] NodeYaml.FindAllNodes -> NodeYaml.GetAllNodeInfo
  - [x] NewInfo -> NewNodeInfo
- [X] reorganize node to be more reasonable
  - [X] internal/pkg/node/datastructure.go
  - [X] internal/pkg/node/constructors.go
  - [X] internal/pkg/node/methods.go
  - [X] internal/pkg/node/modifiers.go
  - [X] internal/pkg/node/transformers.go
  - [X] internal/pkg/node/util.go
- [X] comment-out unused functions
  - GetByName
  - Entry.SetAltB
  - Entry.GotReal
  - Entry.PrintB
  - NetDevEntry.SetFrom
  - NetDevEntry.SetAltFrom
  - NodeYaml.FindByHwaddr
  - NodeYaml.FindByIpaddr
- [ ] comments, tests, renames, and redundancy check
  - [ ] internal/pkg/node/nodeyaml.go
  - [ ] internal/pkg/node/cobra.go
  - [ ] internal/pkg/node/nodeinfo.go
  - [ ] internal/pkg/node/util.go
  - [ ] internal/pkg/node/node.go
  - [ ] internal/pkg/node/nodeconf.go
- [ ] audit wide functions for refactoring

### CODE REVIEW

**Comment by anderbubble** [comment]
@mslacken definitely a work-in-progress, but this is the kind of refactor that I've got in mind. I'm feeling pretty good about it so far: I think I'm mostly unstuck, now it's just about churning through all the things, generating the comments and tests.

That said, let me know if you have any concerns about this.

**Comment by mslacken** [comment]
I think its better to base these changes on #721

**Comment by anderbubble** [comment]
@mslacken I'm rebasing it frequently as `development` is updated, which is going reasonably well so far.

**Comment by anderbubble** [comment]
I've saved this branch for reference, but my thinking on the best way to approach improvement in node has changed significantly, so I'm closing the PR.

**Pull request closed without merging**
