### PR TITLE
Use `go fmt` to standardize code formatting

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

I noticed other developers making seemingly unrelated formatting changes to Go source files in PRs. I inferred that there must be an automated formatting process happening. I found `go fmt` and found that it can run as `go fmt ./...` to format an entire project. I have added that to `Makefile` and run it against the project.

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/development/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/development/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/hpcng/warewulf/tree/development/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [development](https://github.com/hpcng/warewulf/tree/development/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/development/CONTRIBUTORS.md)

### CODE REVIEW

**Review by mslacken — CHANGES_REQUESTED** [review]
I really like the idea of the formatted repo, BUT can we make this a part of the github checks so that you only can make PRs which is formatted right?  I mean something like the Changelog Enforcer.
This will save a loot work in the future.

**Comment by anderbubble** [comment]
> can we make this a part of the github checks so that you only can make PRs which is formatted right?

Agreed.

**Comment by anderbubble** [comment]
@mslacken let me know what you think. I ended up with a bit of a refactor to make the checks all behave the same, and to make it so that we can see their status individually.

**Review by mslacken — APPROVED** [review]
Looks great

**Pull request merged**
