### PR TITLE
Move operational code for configuration out of wwctl 

### PR DESCRIPTION
**Pull request by jcsiadal**
Configuration functions are moved out of wwctl, so that they can be accessed without calling wwctl code. New configuration package implements a single exported function.

Should make it easier to add more configuration options.

Many of the minor code format changes were done automatically by Google's VSCode Go plugin.  

CHANGELOG

Additions

- SafeFileCopy added to util; won't overwrite destination files
- Restores (only missing) iPXE files when TFTP is configured

Changes

- Relocate non-Cobra functional code in 'configure' from wwctl to pkg.
- Convert repeated code in ssh and tftp to loops.
- Make 'show' argument work correctly on all configs

### CODE REVIEW

**Comment by gmkurtzer** [comment]
This needs to be coordinated and merged against #304.

**Comment by jcsiadal** [comment]
Can you merge one of them? One of us can work with the rebase afterward. Git doesn't handle content moves between files, but it's not too complicated to do manually.

**Comment by mslacken** [comment]
Added the host overlay code to this pr so #304 can be closed if this branch is merged.
@jcsiadal  the utilCopyFile is broken at the moment, I get following error
```
[DEBUG]   : Copying 'etc/network/interfaces' to '/tmp/.wwctl-overlay-576494507/etc/network/interfaces'
[ERROR]   : File copy from etc/network/interfaces to /tmp/.wwctl-overlay-576494507/etc/network/interfaces failed.
 write etc/network/interfaces: copy_file_range: bad file descriptor
```
Can you please have a look and fix it before the merge?

**Comment by jcsiadal** [comment]
I reverted filecopy to it's original version and rebased to main.

**Pull request merged**
