### PR TITLE
Addind information related to node status checkup during provisiong p…

### PR DESCRIPTION
**Pull request by ArnaudDevelopper**
I think that adding some information related to the node status command is great for debug sessions

### CODE REVIEW

**Review by mslacken — APPROVED** [review]
Can you please also update CHANGELOG.md in the future?

**Comment by ArnaudDevelopper** [comment]
Yes ! Sorry for the inconvenience

**Comment by mslacken** [comment]
I didn't update the CHANGELOG.md either, but it would be nice if you make bigger changes in the future.

**Comment by ArnaudDevelopper** [comment]
If you prefer to have bigger pull request, I can !
By the way, there is some issues in the formatting : https://warewulf.org/docs/development/contents/provisioning.html

**Pull request merged**
