### PR TITLE
Nil check node configuration pointers.

### PR DESCRIPTION
**Pull request by MatthewHink**
Fixes https://github.com/hpcng/warewulf/issues/366

The CI build will fail since I did not update the failing test yet.

### CODE REVIEW

**Comment by MatthewHink** [comment]
This may be similar to #365 I'm not sure yet.

To set this up I did:
```
git pull origin main
sudo mv  /usr/local/etc/warewulf/ /usr/local/etc/warewulf.prev
sudo make install
```
which gave me the node.conf in #366.

We didn't fail in the past because there were no pointers in the NodeConf structure here: 
https://github.com/hpcng/warewulf/blob/6c0fd068cc7118b8bf9a3f9e901b179a30474858/internal/pkg/node/datastructure.go#L28-L29

This PR adds a nil check and a regression unit test that fails in current mainline with this failure:
```
=== RUN   TestNodeUpdate
--- FAIL: TestNodeUpdate (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x5ac26f]

goroutine 6 [running]:
testing.tRunner.func1.2({0x5d0140, 0x77f6a0})
	/usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x218
panic({0x5d0140, 0x77f6a0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/hpcng/warewulf/internal/pkg/node.(*nodeYaml).NodeUpdate(_, {{{0xc000051b30, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
	/home/mhink/go/src/github.com/hpcng/warewulf/internal/pkg/node/modifiers.go:63 +0x38f
github.com/hpcng/warewulf/internal/pkg/node.TestNodeUpdate(0xc00008eea0)
	/home/mhink/go/src/github.com/hpcng/warewulf/internal/pkg/node/node_test.go:34 +0x185
testing.tRunner(0xc00008eea0, 0x6139a0)
	/usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL	github.com/hpcng/warewulf/internal/pkg/node	0.005s
```

**Comment by mslacken** [comment]
Can you please check if this is needed withupdated main, there are also now `nil` checks involved

**Comment by MatthewHink** [comment]
Looking at this now. We may no longer need this full PR, but the unit test is useful.

**Comment by MatthewHink** [comment]
The unit test is failing because node.Kernel is nil.

**Comment by MatthewHink** [comment]
Rebased this PR. The nil check passes the unit test.

**Review by mslacken — APPROVED** [review]
Great, so this test would have catched the memory bugs for the nodes. 
Do we need also similar tests for the profiles?

**Comment by MatthewHink** [comment]
This test would have caught the failure. I did not investigate profiles, but probably should

**Pull request merged**
