### PR TITLE
refactor profile add alike node add

### PR DESCRIPTION
**Pull request by anderbubble**

### CODE REVIEW

**Comment by anderbubble** [comment]
@mslacken I have been working on this PR to try to address #658 and #659. When I started going down this rabbit hole I found, even after making `wwctl profile add` more like `wwctl node add`, that network devices were not created on new profiles. For example:

```
[janderson@rocky warewulf]$ sudo wwctl node add --netname primary  --netdev eno3 asdf1
Added node: asdf1
ERROR: failed to reload warewulf daemon: Warewulf server is not running
[janderson@rocky warewulf]$ sudo wwctl node list -a asdf1 | grep primary:
asdf1                primary:type       --           (ethernet)
asdf1                primary:onboot     --           --
asdf1                primary:netdev     --           eno3
asdf1                primary:hwaddr     --           --
asdf1                primary:ipaddr     --           --
asdf1                primary:ipaddr6    --           --
asdf1                primary:netmask    --           (255.255.255.0)
asdf1                primary:gateway    --           --
asdf1                primary:mtu        --           --
asdf1                primary:primary    --           true
```

But if I do the same with a profile:

```
[janderson@rocky warewulf]$ sudo wwctl profile add --netname primary  --netdev eno3 asdf1
Added profile: asdf1
ERROR: failed to reload warewulf daemon: Warewulf server is not running
[janderson@rocky warewulf]$ sudo wwctl profile list -a asdf1 | grep primary:
```

I added a whole bunch of `wwlog.Debug` to try to trace this down, which I've left in the PR for your reference. The  closest I've come to finding the problem is that when `NodeAdd` calls `nodeInfo.SetFrom(&nodeConf)` then `nodeInfo` gets updated with the network device...

```
DEBUG  : nodeConf before:
runtime overlay:
- ""
system overlay:
- ""
kernel: {}
ipmi:
  tagsdel:
  - ""
profiles:
- ""
network devices:
  primary:
    device: eno3
    tagsdel:
    - ""
tagsdel:
- ""

DEBUG  : nodeInfo before:
id: {}
comment: {}
clustername: {}
containername: {}
ipxe: {}
runtimeoverlay: {}
systemoverlay: {}
root: {}
discoverable: {}
init: {}
assetkey: {}
kernel:
  override: {}
  args: {}
ipmi:
  ipaddr: {}
  netmask: {}
  port: {}
  gateway: {}
  username: {}
  password: {}
  interface: {}
  write: {}
  tags: {}
profiles: {}
netdevs: {}
tags: {}

DEBUG  : nodeInfo after:
id: {}
comment: {}
clustername: {}
containername: {}
ipxe: {}
runtimeoverlay: {}
systemoverlay: {}
root: {}
discoverable: {}
init: {}
assetkey: {}
kernel:
  override: {}
  args: {}
ipmi:
  ipaddr: {}
  netmask: {}
  port: {}
  gateway: {}
  username: {}
  password: {}
  interface: {}
  write: {}
  tags: {}
profiles: {}
netdevs:
  primary:
    type: {}
    onboot: {}
    device: {}
    hwaddr: {}
    ipaddr: {}
    ipaddr6: {}
    ipcidr: {}
    prefix: {}
    netmask: {}
    gateway: {}
    mtu: {}
    primary: {}
    tags: {}
tags: {}
```

...but when `ProfileAdd` calls `profileInfo.SetFrom(&profileConf)` then `profileInfo` does not get updated with the network device.

```
DEBUG  : profileConf before:
runtime overlay:
- ""
system overlay:
- ""
kernel: {}
ipmi:
  tagsdel:
  - ""
network devices:
  primary:
    device: eno3
    tagsdel:
    - ""
tagsdel:
- ""

DEBUG  : profileInfo before:
id: {}
comment: {}
clustername: {}
containername: {}
ipxe: {}
runtimeoverlay: {}
systemoverlay: {}
root: {}
discoverable: {}
init: {}
assetkey: {}
kernel: null
ipmi: null
profiles: {}
netdevs: {}
tags: {}

DEBUG  : profileInfo after:
id: {}
comment: {}
clustername: {}
containername: {}
ipxe: {}
runtimeoverlay: {}
systemoverlay: {}
root: {}
discoverable: {}
init: {}
assetkey: {}
kernel:
  override: {}
  args: {}
ipmi:
  ipaddr: {}
  netmask: {}
  port: {}
  gateway: {}
  username: {}
  password: {}
  interface: {}
  write: {}
  tags: {}
profiles: {}
netdevs: {}
tags: {}
```

Both `profileInfo` and `nodeInfo` are of type `NodeInfo`, and they are running the same `SetFrom` function. I can't find where in that function the behavior ends up diverging between the two cases, but I get lost in all the reflection in `SetFrom`.

Could you help me figure out what's going on? And if I'm going down the completely wrong track, let me know that, too.

**Comment by mslacken** [comment]
I tried to reproduce this, but I think the problem here is that `profile show` even wtih `-a` does not show the network device. So its in the config, but not displayed.

**Comment by mslacken** [comment]
See #676 for a refactored and so better `profile list`

**Comment by anderbubble** [comment]
It's at least not in the config in my branch / after this PR.

```
[janderson@rocky warewulf]$ sudo wwctl profile add --netname primary  --netdev eno3 asdf1
Added profile: asdf1
ERROR: failed to reload warewulf daemon: Warewulf server is not running

[janderson@rocky warewulf]$ sudo head /etc/warewulf/nodes.conf 
WW_INTERNAL: 43
nodeprofiles:
  asdf1: {}
  default:
    comment: This profile is automatically included for each node
    network devices:
      default:
        type: Ethernet
        mtu: "9000"
nodes:

```

I'll try it with your PR in #670

**Comment by anderbubble** [comment]
@mslacken I tried this with your PR #670, and it's broken there as well.

```
[janderson@rocky warewulf]$ sudo wwctl profile add --netname primary  --netdev eno3 asdf1
Added profile: asdf1
[janderson@rocky warewulf]$ sudo head /etc/warewulf/nodes.conf 
WW_INTERNAL: 43
nodeprofiles:
  asdf1: {}
  default:
    comment: This profile is automatically included for each node
    network devices:
      default:
        type: Ethernet
        mtu: "9000"
nodes:
```

The original code implements this by running `ProfileSet` after `AddProfile`, but this is prone to error. Both of our PRs remove the call the `ProfileSet`, but `AddProfile` (or `ProfileAdd` in my case) doesn't successfully set the parameters of the added profile like it does for nodes, and I can't figure out why.

**Comment by JasonYangShadow** [comment]
> 



> @mslacken I tried this with your PR #670, and it's broken there as well.
> 
> ```
> [janderson@rocky warewulf]$ sudo wwctl profile add --netname primary  --netdev eno3 asdf1
> Added profile: asdf1
> [janderson@rocky warewulf]$ sudo head /etc/warewulf/nodes.conf 
> WW_INTERNAL: 43
> nodeprofiles:
>   asdf1: {}
>   default:
>     comment: This profile is automatically included for each node
>     network devices:
>       default:
>         type: Ethernet
>         mtu: "9000"
> nodes:
> ```
> 
> The original code implements this by running `ProfileSet` after `AddProfile`, but this is prone to error. Both of our PRs remove the call the `ProfileSet`, but `AddProfile` (or `ProfileAdd` in my case) doesn't successfully set the parameters of the added profile like it does for nodes, and I can't figure out why.

also it looks like that there is no such nodes.conf
```
[vagrant@localhost warewulf]$ sudo head /etc/warewulf/nodes.conf 
head: cannot open '/etc/warewulf/nodes.conf' for reading: No such file or directory
```

**Comment by mslacken** [comment]
> 
> ```
> [vagrant@localhost warewulf]$ sudo head /etc/warewulf/nodes.conf 
> head: cannot open '/etc/warewulf/nodes.conf' for reading: No such file or directory
> ```
The branch needs to be rebased the actual development tree as there you can point warewulf to an arbitrary `nodes.conf` which helps a lot for testing

**Comment by JasonYangShadow** [comment]
> > ```
> > [vagrant@localhost warewulf]$ sudo head /etc/warewulf/nodes.conf 
> > head: cannot open '/etc/warewulf/nodes.conf' for reading: No such file or directory
> > ```
> 
> The branch needs to be rebased the actual development tree as there you can point warewulf to an arbitrary `nodes.conf` which helps a lot for testing

Thanks! I am actually testing using the latest `development` branch locally, I plan to create another PR if refactoring is needed.  This PR is only for reference and guidance.

**Comment by anderbubble** [comment]
I'm closing this as it's fallen behind current development. If I want to work on this again, I'd start over.

**Pull request closed without merging**
