### PR TITLE
Arm kernel support

### PR DESCRIPTION
**Pull request by gmkurtzer**
An implementation of PR #120 for issue #119.

### CODE REVIEW

**Comment by mslacken** [comment]
I could import the kernel and it got uncompressed, still I could not boot the it. This could also be a issue with my underlying virtual hardware. 
Still this patch keeps trying to search for a `vmlinuz` which is a x86_64 specific name.

**Comment by rhenwood-arm** [comment]
@mslacken I had success with virtual hardware on AArch64... as well as a x86 virtual host running with QEMU. I unziped my kernel and named it `vmlinuz` for convenience.

I followed (something like) these instructions: https://warewulf.hpcng.org/docs/contributing/development-environment-kvm

What error are you seeing?

**Comment by mslacken** [comment]
i always see the error 
```
Could not select: Exec format error (http://ipxe.org/2e008081)
```
As far as I see it from the logs, the kernel is delivered, see
```
[Tue Sep 21 16:08:06 CEST 2021] SEND:            arm01: /var/lib/warewulf/provision/kernel/5.3.18-59.19-default/vmlinuz
```
and it has the right format
```
/var/lib/warewulf/provision/kernel/5.3.18-59.19-default/vmlinuz: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), statically linked, BuildID[sha1]=7f1094f51de7ab74a2ee5096f88c7615a0dbf16b, not stripped
```

**Comment by gmkurtzer** [comment]
@mslacken You mentioned that `vmlinuz` is an x86 specific name. My bad. What is the ARM specific name?

Can you copy your system kernel to a temporary name, decompress it, and see what is different between that and what Warewulf is dropping in `/var/lib/provision/kernel/*/vmlinuz`?

**Comment by gmkurtzer** [comment]
> @mslacken I had success with virtual hardware on AArch64... as well as a x86 virtual host running with QEMU. I unziped my kernel and named it `vmlinuz` for convenience.

@rhenwood-arm I'd like to ensure that you don't have to uncompress or move your vmlinuz. It should be uncompressing the kernel automatically now. what kernel name are you seeing?

**Comment by mslacken** [comment]
Still can't boot the arm kerel with following error
```
================================================================================
Warewulf v4 now booting: arm01

Container: leap15.3-arm
Kernel: 5.3.18-59.19-default
KernelArgs: crashkernel=no vga=791 rootfstype=rootfs

http://192.168.100.250:9873/kernel/52-54-00-0f-75-a0... ok
[Security] 3rd party image[0] can be loaded after EndOfDxe: .
InstallProtocolInterface: 5B1B31A1-9562-11D2-8E3F-00A0C969723B 43A5AB140
Unloading driver at 0x00000000000
Could not select: Exec format error (http://ipxe.org/2e008081)

There was an error, rebooting in 15s...
```

**Comment by gmkurtzer** [comment]
@mslacken What is the differences between the kernel that Warewulf cached and t he system kernel (once gunzipped)?

**Comment by mslacken** [comment]
@gmk I can't use the system kernel as the host running warewulf is on x86_64

**Comment by gmkurtzer** [comment]
@mslacken There could be other factors going on then in a heterogenous environment.

How are you importing a kernel that isn't the same architecture as your host?

**Comment by gmkurtzer** [comment]
I am merging *THIS* PR as it is blocking other things. If there are any bugs with this release, let's please patch and fix them as necessary. Thanks!

**Pull request merged**
