### PR TITLE
Refactor `profile add` to make it like `node add`

### LINKED ISSUE #658: wwctl profile add always adds
### Version of Warewulf

4.4

### Expected behavior

`wwctl profile add myprofile` prompts for whether to create a profile, but it should not create it if you say no.

### Actual behavior

The profile is created anyway.

### Steps to reproduce this behavior

`wwctl profile add myprofile` and say no.

### What OS/distro are you running

Rocky Linux 9.1

### How did you install Warewulf

Packages from github.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):
Refactor `profile add` to make it like `node add

### This fixes or addresses the following GitHub issues:

 - Fixes #658 #659 

#### Before submitting a PR, make sure you have done the following:

- Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/development/contributing/contributing.html)
- Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/development/CHANGELOG.md) if necessary
- Updated [userdocs](https://github.com/hpcng/warewulf/tree/development/userdocs) if necessary
- Based this PR against the appropriate branch (typically [development](https://github.com/hpcng/warewulf/tree/development/userdocs))
- Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/development/CONTRIBUTORS.md

### CODE REVIEW

**Comment by JasonYangShadow** [comment]
@anderbubble @mslacken please help take a look at this PR and see if the requirements are met. Thanks!

**Comment by mslacken** [comment]
@JasonYangShadow can you please rebase so that we can merge that?

**Comment by anderbubble** [comment]
I'm going to test this now, particularly in case it fixes #782

**Comment by anderbubble** [comment]
I confirmed that this fixes #782.

```console
$ sudo wwctl profile add asdf3 --comment "a test profile" --netdev eth0 --yes
$ sudo wwctl profile list asdf3 -a
  PROFILE  FIELD            PROFILE  VALUE           
  asdf3    Id               --       asdf3           
  asdf3    comment          --       a test profile  
  asdf3    cluster          --       --              
  asdf3    container        --       --              
  asdf3    ipxe             --       --              
  asdf3    runtime          --       --              
  asdf3    wwinit           --       --              
  asdf3    root             --       --              
  asdf3    discoverable     --       --              
  asdf3    init             --       --              
  asdf3    asset            --       --              
  asdf3    kerneloverride   --       --              
  asdf3    kernelargs       --       --              
  asdf3    ipmiaddr         --       --              
  asdf3    ipminetmask      --       --              
  asdf3    ipmiport         --       --              
  asdf3    ipmigateway      --       --              
  asdf3    ipmiuser         --       --              
  asdf3    ipmipass         --       --              
  asdf3    ipmiinterface    --       --              
  asdf3    ipmiwrite        --       --              
  asdf3    profile          --       --              
  asdf3    primarynet       --       --              
  asdf3    default:type     --       --              
  asdf3    default:onboot   --       --              
  asdf3    default:netdev   --       eth0            
  asdf3    default:hwaddr   --       --              
  asdf3    default:ipaddr   --       --              
  asdf3    default:ipaddr6  --       --              
  asdf3    default:netmask  --       --              
  asdf3    default:gateway  --       --              
  asdf3    default:mtu      --       --              
  asdf3    default:primary  --       --
```

There's a merge conflict, but it was easy enough for me to do myself. I also updated failing tests to reflect changes from #780

**Pull request merged**
