### PR TITLE
overlays from different profiles are merged

### LINKED ISSUE #885: merge overlays from multiple profiles
Right now, overlay lists from multiple profiles override each other entirely. So in this configuration:

```
nodeprofiles:
  profile1:
    runtime overlay:
    - overlay1
    - overlay2
  profile2:
    runtime overlay:
    - overlay2
    - overlay3

nodes:
  node1:
    profiles:
    - profile1
    - profile2
```

`node1` ultimately gets overlays `overlay2,overlay3` because the entirety of the runtime overlay specification from profile2 overrides profile1.

There should be a mechanism for allowing overlays from multiple profiles to be included in a final node. For example, perhaps in the above situation the node should have overlays 1, 2, and 3. Or perhaps there should be a syntax like

```
  profile2:
    runtime overlay:
    - +overlay2
    - +overlay3
```

to add overlays, and

```
  profile2:
    runtime overlay:
    - -overlay2
    - -overlay3
```

to remove overlays.

### PR DESCRIPTION
**Pull request by mslacken**
If a node contains several profiles and these profiles have
overlays attached, these profiles are now merged. Overlays
can't be excluded as this can not be displayed to the user

close #885

### CODE REVIEW

**Comment by mslacken** [comment]
@griznog please check the tests which are included in this PR

**Comment by mslacken** [comment]
close #507

**Comment by griznog** [comment]
I tested this in my test environment and there it properly merges overlays and the result looks great. I'd vote to merge it into `development`. I can't really test this in  my more complex main environment without re-factoring a lot of my existing profile design which currently works around the lack of this feature. If this merged into `development` that'll be extra encouragement for me to do that.  Thanks, @mslacken !

**Comment by mslacken** [comment]
We decided to move this into 4.5.0 if you also support this. Lets wait for @anderbubble review.

**Comment by griznog** [comment]
@mslacken  @anderbubble Is this ready and/or can this be merged into `development`? I'd like to test in my main environment where I have the most complex collection of overlays. Since that environment is running the latest `development` I'm not sure if switching to this PR will roll back some other thing in that branch I'm already depending on.

**Comment by anderbubble** [comment]
I'm sorry, I still haven't looked at it; but, at the very least, I'll get it rebased so you can switch to it.

**Comment by anderbubble** [comment]
When value is empty, this is showing up in list output:

```
  n2    RuntimeOverlay  ,p1      a,b,c
```

Note the leading comma.

I think I see how to fix this, so I'll give it a try.

**Review by anderbubble — APPROVED** [review]
I removed a redundant CHANGELOG entry and fixed the inclusion of an initial empty "from" value. Functionality appears to work as expected.

**Pull request merged**
